USE festival_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ParticipantEvent;
DROP TABLE IF EXISTS GlobalTalkSeat;

DROP TABLE IF EXISTS CampEatsFoodType;
DROP TABLE IF EXISTS FunZoneGames;

DROP TABLE IF EXISTS CampEats;
DROP TABLE IF EXISTS Concert;
DROP TABLE IF EXISTS DJ;
DROP TABLE IF EXISTS FunZone;
DROP TABLE IF EXISTS GlobalTalks;

DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS TicketUnder25;
DROP TABLE IF EXISTS Participant;
DROP TABLE IF EXISTS Ticket;

DROP TABLE IF EXISTS Game;
DROP TABLE IF EXISTS Organizer;
DROP TABLE IF EXISTS FestivalDay;

SET FOREIGN_KEY_CHECKS = 1;
